version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: user
      POSTGRES_DB: test
    networks:
      local:
        aliases:
          - postgres.local

networks:
  local: