// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"jocer/internal/storage/ent/jock"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// JockCreate is the builder for creating a Jock entity.
type JockCreate struct {
	config
	mutation *JockMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (jc *JockCreate) SetName(s string) *JockCreate {
	jc.mutation.SetName(s)
	return jc
}

// SetContent sets the "content" field.
func (jc *JockCreate) SetContent(s string) *JockCreate {
	jc.mutation.SetContent(s)
	return jc
}

// SetID sets the "id" field.
func (jc *JockCreate) SetID(u uuid.UUID) *JockCreate {
	jc.mutation.SetID(u)
	return jc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (jc *JockCreate) SetNillableID(u *uuid.UUID) *JockCreate {
	if u != nil {
		jc.SetID(*u)
	}
	return jc
}

// Mutation returns the JockMutation object of the builder.
func (jc *JockCreate) Mutation() *JockMutation {
	return jc.mutation
}

// Save creates the Jock in the database.
func (jc *JockCreate) Save(ctx context.Context) (*Jock, error) {
	jc.defaults()
	return withHooks[*Jock, JockMutation](ctx, jc.sqlSave, jc.mutation, jc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jc *JockCreate) SaveX(ctx context.Context) *Jock {
	v, err := jc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jc *JockCreate) Exec(ctx context.Context) error {
	_, err := jc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jc *JockCreate) ExecX(ctx context.Context) {
	if err := jc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jc *JockCreate) defaults() {
	if _, ok := jc.mutation.ID(); !ok {
		v := jock.DefaultID()
		jc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jc *JockCreate) check() error {
	if _, ok := jc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Jock.name"`)}
	}
	if v, ok := jc.mutation.Name(); ok {
		if err := jock.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Jock.name": %w`, err)}
		}
	}
	if _, ok := jc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Jock.content"`)}
	}
	return nil
}

func (jc *JockCreate) sqlSave(ctx context.Context) (*Jock, error) {
	if err := jc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	jc.mutation.id = &_node.ID
	jc.mutation.done = true
	return _node, nil
}

func (jc *JockCreate) createSpec() (*Jock, *sqlgraph.CreateSpec) {
	var (
		_node = &Jock{config: jc.config}
		_spec = sqlgraph.NewCreateSpec(jock.Table, sqlgraph.NewFieldSpec(jock.FieldID, field.TypeUUID))
	)
	if id, ok := jc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := jc.mutation.Name(); ok {
		_spec.SetField(jock.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := jc.mutation.Content(); ok {
		_spec.SetField(jock.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	return _node, _spec
}

// JockCreateBulk is the builder for creating many Jock entities in bulk.
type JockCreateBulk struct {
	config
	builders []*JockCreate
}

// Save creates the Jock entities in the database.
func (jcb *JockCreateBulk) Save(ctx context.Context) ([]*Jock, error) {
	specs := make([]*sqlgraph.CreateSpec, len(jcb.builders))
	nodes := make([]*Jock, len(jcb.builders))
	mutators := make([]Mutator, len(jcb.builders))
	for i := range jcb.builders {
		func(i int, root context.Context) {
			builder := jcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jcb *JockCreateBulk) SaveX(ctx context.Context) []*Jock {
	v, err := jcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jcb *JockCreateBulk) Exec(ctx context.Context) error {
	_, err := jcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jcb *JockCreateBulk) ExecX(ctx context.Context) {
	if err := jcb.Exec(ctx); err != nil {
		panic(err)
	}
}
